sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - /^v\d.*$/
    - master
    - develop

php:
  - 5.6
  - 7.1

env:
  - WP_VERSION=4.4 WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=0

matrix:
  fast_finish: true
  exclude:
    - php: 7.1
      env: WP_VERSION=4.4 WP_MULTISITE=0

install:
  - export DEV_LIB_PATH=bin/dev-lib
  - export DEV_LIB_SKIP=codeception,jscs,jshint,yuicompressor,phpunit,xmllint
  - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
  - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/xwp/wp-dev-lib.git $DEV_LIB_PATH; fi
  - source $DEV_LIB_PATH/travis.install.sh

script:
  - source $DEV_LIB_PATH/travis.script.sh

after_script:
  - source $DEV_LIB_PATH/travis.after_script.sh

before_deploy:
  - npm install
  # Regenerate our documentation to include any new actions/filters
  - grunt docs
  # Build the plugin for deployment
  - grunt build

deploy:
  provider: releases
  api_key:
    secure: Ac2rMLhmObDfpQ2FNN90oChJ6LEgBmAoimKgaNxkcrE3qcrLvBV60Byfl3mNPUn9uV3l342Cus7upbJVL2yZFLPGqRpAT2zpPRmrns6L12I13m8BjdxJBysFFa4cePYgK12DgfmR2yKm+wM5OlI1rKyqrUlJN9kpHGjqt4DKa1TLOCiDhLJDFoba1QCE4+E6XdgtxNnG8Z55DDjB9h8c+Fl07Gfw/nmG5YJ7Xb+vG30r5Iy4X7ibfPgW7XJafS/FmRhGCtEsAaVwRL4CBJSFWQmEwFyPwke1CEjMAHd0q4Kyb+8fOiTP1YNSsxNSIkU1GLCx10lpgBP8fe5W+GEfd3j4n2C6ogfuCYMZhcEodm2897D1OoDZeaiXaKyy6qDUcx+m/pTNsDfRkewQdtl5NTE04jyldv7L8xlSlCCTS5E3oFT5tQme6bJQMKwZ4s0AVWYuLwUGijOQzaZU1ZrUfuhpyfugj+1ICypxdksIH/hev/LtuYRqbg6UQCocs8hrtAgCwCmSLb6nXNHHDIJhZGDTmF+ZXz5487tru9p45VdE7Gxfq2UfZxZRmnmlSuLut20B6IJkca7HlSocULqtCaYdMnK+e4ageGtJEcV2dnNEDaXd+kY4ktSz2/Uf8hjJiKWAdkBJYSTmDTZzOAj0TrBQ0ff3/sHk3YQg2nkOFn0=
  file_glob: true
  file: site-speed-monitor-*.zip
  on:
    tags: true
    repo: CodeParrots/site-speed-monitor
    php: '7.1'
    condition: "$WP_VERSION=trunk"
  skip_cleanup: true
  overwrite: true
